-- Drop tables in correct order due to dependencies
drop table if exists predictions;
drop table if exists game_odds;
drop table if exists nba_schedule;
drop table if exists team_stats;

-- Create team_stats table first (as it's referenced by others)
create table team_stats (
    id bigint generated by default as identity primary key,
    team_name text not null,
    team_code text not null unique,
    ppg numeric(5,1) not null,
    oppg numeric(5,1) not null,
    pace numeric(5,1) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create nba_schedule table
create table nba_schedule (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    home_team text not null,
    away_team text not null,
    team_id_home text not null,
    team_id_away text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint nba_schedule_team_id_home_fkey foreign key (team_id_home) references team_stats(team_code) deferrable initially deferred,
    constraint nba_schedule_team_id_away_fkey foreign key (team_id_away) references team_stats(team_code) deferrable initially deferred
);

-- Create game_odds table with reference to nba_schedule
create table game_odds (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    spread_home numeric not null,
    total numeric not null,
    home_moneyline integer,
    away_moneyline integer,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint game_odds_game_id_fkey foreign key (game_id) references nba_schedule(game_id) deferrable initially deferred
);

-- Create predictions table
create table predictions (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    home_team text not null,
    away_team text not null,
    team_id_home text not null,
    team_id_away text not null,
    predicted_home_score integer not null,
    predicted_away_score integer not null,
    predicted_total integer not null,
    fanduel_spread_home numeric not null,
    fanduel_total numeric not null,
    home_moneyline integer,
    away_moneyline integer,
    actual_home_score integer,
    actual_away_score integer,
    spread_result text check (spread_result in ('win', 'loss', 'push')),
    total_result text check (total_result in ('win', 'loss', 'push')),
    game_status text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint predictions_game_id_fkey foreign key (game_id) references nba_schedule(game_id) deferrable initially deferred,
    constraint predictions_team_id_home_fkey foreign key (team_id_home) references team_stats(team_code) deferrable initially deferred,
    constraint predictions_team_id_away_fkey foreign key (team_id_away) references team_stats(team_code) deferrable initially deferred
);

-- Create indexes for better query performance
create index nba_schedule_game_date_idx on nba_schedule(game_date);
create index game_odds_game_date_idx on game_odds(game_date);
create index predictions_game_date_idx on predictions(game_date);