-- Drop existing table if it exists
drop table if exists game_scores;

-- Create game_scores table with the exact schema needed
create table game_scores (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    game_id text not null unique,
    away_team text not null,
    home_team text not null,
    away_score integer not null,
    home_score integer not null,
    game_status text not null,
    game_clock text,
    game_time text
);

-- Create indexes for better query performance
create index game_scores_game_id_idx on game_scores(game_id);
create index game_scores_game_status_idx on game_scores(game_status);