-- Create schedule table
create table if not exists nba_schedule (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    home_team text not null,
    away_team text not null,
    game_time text,
    arena text,
    city text,
    state text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for better query performance
create index nba_schedule_game_date_idx on nba_schedule(game_date);
create index nba_schedule_teams_idx on nba_schedule(home_team, away_team);