-- Drop all tables and recreate with correct schema
drop table if exists predictions;
drop table if exists game_odds;
drop table if exists nba_schedule;
drop table if exists team_stats;

-- Create team_stats table first
create table team_stats (
    id bigint generated by default as identity primary key,
    team_name text not null,
    team_code text not null unique,
    ppg numeric(5,1) not null,
    oppg numeric(5,1) not null,
    pace numeric(5,1) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create nba_schedule table
create table nba_schedule (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    home_team text not null,
    away_team text not null,
    team_id_home text not null references team_stats(team_code),
    team_id_away text not null references team_stats(team_code),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create game_odds table
create table game_odds (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    spread_home numeric not null,
    total numeric not null,
    home_moneyline integer,
    away_moneyline integer,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create predictions table
create table predictions (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    home_team text not null,
    away_team text not null,
    team_id_home text not null references team_stats(team_code),
    team_id_away text not null references team_stats(team_code),
    predicted_home_score integer not null,
    predicted_away_score integer not null,
    predicted_total integer not null,
    fanduel_spread_home numeric not null,
    fanduel_total numeric not null,
    home_moneyline integer,
    away_moneyline integer,
    actual_home_score integer,
    actual_away_score integer,
    spread_result text check (spread_result in ('win', 'loss', 'push')),
    total_result text check (total_result in ('win', 'loss', 'push')),
    game_status text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes
create index nba_schedule_game_date_idx on nba_schedule(game_date);
create index game_odds_game_date_idx on game_odds(game_date);
create index predictions_game_date_idx on predictions(game_date);

-- Insert team stats
insert into team_stats (team_name, team_code, ppg, oppg, pace) values
('Atlanta', 'ATL', 114.9, 119.6, 103.3),
('Boston', 'BOS', 121.5, 111.8, 97.3),
('Brooklyn', 'BKN', 111.7, 114.7, 96.3),
('Charlotte', 'CHA', 110.1, 114.5, 97.7),
('Chicago', 'CHI', 115.4, 122.9, 104.2),
('Cleveland', 'CLE', 123.5, 111.2, 99.8),
('Dallas', 'DAL', 115.6, 109.3, 98.1),
('Denver', 'DEN', 116.5, 115.1, 100.2),
('Detroit', 'DET', 110.4, 111.6, 97.8),
('Golden State', 'GSW', 119.6, 109.1, 101.7),
('Houston', 'HOU', 114.6, 106.2, 100.3),
('Indiana', 'IND', 114.3, 118.4, 99.5),
('LA Clippers', 'LAC', 108.9, 108.1, 97.6),
('LA Lakers', 'LAL', 117.3, 116.2, 99.0),
('Memphis', 'MEM', 118.9, 112.6, 104.1),
('Miami', 'MIA', 110.9, 110.1, 97.2),
('Milwaukee', 'MIL', 111.3, 112.2, 98.6),
('Minnesota', 'MIN', 113.3, 111.0, 98.1),
('New Orleans', 'NOP', 103.5, 115.4, 96.3),
('New York', 'NYK', 118.3, 111.9, 96.0),
('Oklahoma City', 'OKC', 114.3, 103.6, 100.5),
('Orlando', 'ORL', 106.8, 103.2, 97.5),
('Philadelphia', 'PHI', 103.9, 112.6, 96.6),
('Phoenix', 'PHX', 112.1, 114.5, 96.8),
('Portland', 'POR', 106.8, 113.8, 100.3),
('Sacramento', 'SAC', 116.9, 113.7, 98.6),
('San Antonio', 'SAS', 110.1, 110.1, 98.7),
('Toronto', 'TOR', 113.2, 118.6, 98.9),
('Utah', 'UTA', 108.7, 119.3, 99.7),
('Washington', 'WAS', 109.9, 124.7, 103.0);