-- Create game_odds table
create table if not exists game_odds (
    id bigint generated by default as identity primary key,
    game_id text not null unique,
    game_date text not null,
    spread_home numeric not null,
    total numeric not null,
    home_moneyline integer,
    away_moneyline integer,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes
create index if not exists game_odds_game_id_idx on game_odds(game_id);
create index if not exists game_odds_game_date_idx on game_odds(game_date);