name: Update NBA Predictions

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 UTC (5:00 AM EST)
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate environment variables
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_KEY" ]; then
            echo "Error: SUPABASE_KEY is not set"
            exit 1
          fi
          if [ -z "$RAPIDAPI_KEY" ]; then
            echo "Error: RAPIDAPI_KEY is not set"
            exit 1
          fi
          if [ -z "$RAPIDAPI_HOST" ]; then
            echo "Error: RAPIDAPI_HOST is not set"
            exit 1
          fi

      - name: Update predictions and scores
        run: node scripts/update-predictions.js